export default {
  config: {
    audioDir: 'C:\\Users\\Admin\\Music\\Amb Cats',
    outputFile: 'output.mp3',
    duration: 15 * 4 * 5,
    chunkDuration: 15,
    scheduleGranularity: 0.01,
    frequencyUnit: 1,
    volume: 2,
  },
  layers: {
    bg: {
      isConstant: true,
      category: 'amb',
      volume: 1,
      sets: 'amb_mainframe_inactive.exa.ogg',
      intensity: {
        0: { volume: 0.5, frequency: 0 },
      },
      variance: 0,
      bufferBetweenSounds: true,
    },
    drip: {
      category: 'drp',
      volume: 0.1,
      sets: {
        solo: 'water_drips_((0[4-9])|([1-9][0-9])).ogg',
        norm: 'water_drips_0[0-3].ogg',
      },
      intensity: {
        0: { volume: 0.1, solo_frequency: 1 / 10, norm_frequency: 1 / 10 },
        0.5: { volume: 0.5, solo_frequency: 1 / 4, norm_frequency: 1 / 10 },
        1: { volume: 1, solo_frequency: 1 / 2, norm_frequency: 1 / 10 },
        2: { volume: 3, solo_frequency: 1 / 2, norm_frequency: 1 / 2 },
      },
      variance: 0.25,
      directionality: 'unique',
      pitchSpeedRange: [0.9, 1.1],
    },
    breath: {
      isConstant: true,
      category: 'isc',
      volume: 5,
      sets: {
        in: 'isac_vx_breathing_hlmt01_(0[0-4]).ogg',
        out: 'isac_vx_breathing_hlmt01_(0[5-9]).ogg',
        // asphyx: 'isac_vx_breath_asphyxiation_hlmt01_\\d{2}.ogg',
      },
      intensity: {
        0: { volume: 1, frequency: 1 / 2.5 },
        2: { volume: 5, frequency: 2 },
      },
      variance: 0.1,
      directionality: 'none',
      cycleThrough: 'sets',
      bufferBetweenSounds: true,
    },
    heartbeat: {
      isConstant: true,
      category: 'isc',
      volume: 1,
      sets: {
        systolic: 'marker_heartbeat_01_boom_ba_seq_00.ogg',
        diastolic: 'marker_heartbeat_01_boom_ba_seq_01.ogg',
      },
      intensity: {
        0.5: {
          volume: 1,
          systolic_frequency: 1 / 0.6,
          diastolic_frequency: 1 / 0.4,
        },
        1: {
          volume: 2,
          systolic_frequency: 1 / 0.425,
          diastolic_frequency: 1 / 0.325,
        },
        1.5: {
          volume: 4,
          systolic_frequency: 1 / 0.32,
          diastolic_frequency: 1 / 0.28,
        },
        2: {
          volume: 6,
          systolic_frequency: 1 / 0.18,
          diastolic_frequency: 1 / 0.22,
        },
      },
      variance: 0.1,
      directionality: 'none',
      cycleThrough: 'sets',
    },
    // room: {
    //   category: 'amb',
    //   volume: 0.01,
    //   sets: {
    //     norm: 'amb_generic_room_tone_\\d{2}.exa.ogg',
    //   },
    //   intensity: {
    //     0: { volume: 0.1, frequency: 1 },
    //     2: { volume: 0.1, frequency: 1 },
    //   },
    //   variance: 0,
    //   directionality: 'none',
    //   bufferBetweenSounds: true,
    // },
    clang: {
      category: 'met',
      volume: 0.1,
      sets: [
        'amb_air_release_\\d{2}.ogg',
        'amb_glass_stress_\\d{2}.ogg',
        'amb_ship_damage_\\d{2}.ogg',
        'amb_quadshot_airvent_scuffles_\\d{2}.exa.ogg',
        'amb_quadshot_pipe_stress_(lite|med|lrg)_[a-z]_\\d{2}\\.exa\\.ogg',
        'aud_church_hallways_01_\\d{2}.ogg',
        'aud_indoc_center_01_\\d{2}.ogg',
        'aud_observation_center_01_\\d{2}.ogg',
        'aud_pastor_vent_01_\\d{2}.ogg',
        'bing_stairwell_\\d{2}.exa.ogg',
        'creepy_tram_metal_lt_\\d{2}.ogg',
        'crypt_coldsuit_room_\\d{2}.ogg',
        'prop_pipe_plates_thunk_01_\\d{2}.ogg',
        'safe_room_\\d{2}.ogg',
        'sonar_room_z01_\\d{2}.ogg',
        'ssfx_bing_stairwell_\\d{2}.exa.ogg',
        'ssfx_ship_creak_\\d{2}.exa.ogg',
        'zerog_z01_\\d{2}.ogg',
      ],
      intensity: {
        0: { volume: 0.5, frequency: 1 / 20 },
        1.5: { volume: 1, frequency: 1 / 10 },
        2: { volume: 2, frequency: 1 / 5 },
      },
      variance: 0.5,
      directionality: 'unique',
      pitchSpeedRange: [0.9, 1.1],
    },
    annc: {
      category: 'sfx',
      volume: 0.25,
      sets: 'audio_pa_02_04.exa.ogg',
      intensity: {
        0: { volume: 0.15, frequency: 1 / 45 },
        2: { volume: 0.15, frequency: 1 / 45 },
      },
      variance: 0,
      directionality: 'shared',
    },
    guide_annc: {
      category: 'npc',
      volume: 2,
      sets: 'audio_pa_03_\\d{2}.exa.ogg',
      intensity: {
        0: { volume: 0.25, frequency: 1 / 2 },
      },
      variance: 0,
      // directionality: 'shared',
      cycleThrough: 'files',
      bufferBetweenSounds: true,
    },
    crazy: {
      category: 'npc',
      volume: 0.25,
      sets: 'observation_z01_\\d{2}.ogg',
      intensity: { 0: { volume: 0.25, frequency: 1 } },
      bufferBetweenSounds: true,
      variance: 0,
      directionality: 'shared',
    },
  },
}
