export default {
  config: {
    audioDir: '/home/personal/Music/DS/',
    outputFile: 'output.mp3',
    duration: 15 * 1 * 5,
    chunkDuration: 15,
    scheduleGranularity: 0.01,
    frequencyUnit: 1,
    volume: 2,
  },
  director: {
    minLayers: 4,
    maxLayers: 6,
    minDuration: 60 * 5,
    maxDuration: 60 * 15,
  },
  layers: {
    // mus: {
    //   category: 'mus',
    //   volume: 1,
    //   sets: {
    //     0: '37. Ch03 Outer Decon Room 01.mp3',
    //     1: '38. Ch03 Outer Decon Room 02.mp3',
    //     2: '39. Ch03 Outer Decon Room 03.mp3',
    //     3: '40. Ch03 Outer Decon Room 04.mp3',
    //   },
    //   intensity: {
    //     0: {
    //       '0_volume': 2,
    //       '1_volume': 0,
    //       '2_volume': 0,
    //       '3_volume': 0,
    //       volume: 1,
    //     },
    //     1.5: {
    //       '0_volume': 2,
    //       '1_volume': 2,
    //       '2_volume': 0,
    //       '3_volume': 0,
    //       volume: 1,
    //     },
    //   },
    //   variance: 0,
    //   frequency: 0,
    //   bufferBetweenSounds: true,
    // },
    bg: {
      isConstant: true,
      category: 'amb',
      volume: 1,
      sets: 'amb_mainframe_inactive.exa.ogg',
      intensity: {
        0: { volume: 0.5, frequency: 0 },
      },
      variance: 0,
      bufferBetweenSounds: true,
      cycleMode: 'set',
    },
    drip: {
      category: 'drp',
      volume: 0.1,
      sets: {
        solo: 'water_drips_((0[4-9])|([1-9][0-9])).ogg',
        norm: 'water_drips_0[0-3].ogg',
      },
      intensity: {
        0: { volume: 0.1, solo_frequency: 1 / 10, norm_frequency: 1 / 10 },
        0.5: { volume: 0.5, solo_frequency: 1 / 4, norm_frequency: 1 / 10 },
        1: { volume: 1, solo_frequency: 1 / 2, norm_frequency: 1 / 10 },
        2: { volume: 3, solo_frequency: 1 / 2, norm_frequency: 1 / 2 },
      },
      variance: 0.25,
      directionality: 'unique',
      pitchSpeedRange: [0.9, 1.1],
    },
    breath: {
      isConstant: true,
      category: 'isc',
      volume: 5,
      sets: {
        in: [
          'isac_vx_breathing_hlmt01_(0[0-4]).ogg',
          // 'isac_vx_breathing_hlmt01_(10|12).ogg',
          // 'isac_vx_breathing_hlmt01_19.ogg',
          // 'isac_vx_breathing_hlmt01_(2[0-1]).ogg',
          // 'isac_vx_breathing_hlmt01_(2[8-9]).ogg',
          // 'isac_vx_breathing_hlmt01_(3[0-2]).ogg',
        ],
        out: [
          'isac_vx_breathing_hlmt01_(0[5-9]).ogg',
          // 'isac_vx_breathing_hlmt01_11.ogg',
          // 'isac_vx_breathing_hlmt01_(1[3-8]).ogg',
          // 'isac_vx_breathing_hlmt01_(2[2-7]).ogg',
          // 'isac_vx_breathing_hlmt01_(3[3-7]).ogg',
        ],
        // asphyx: 'isac_vx_breath_asphyxiation_hlmt01_\\d{2}.ogg',
      },
      intensity: {
        0: { volume: 1, frequency: 20 },
        2: { volume: 5, frequency: 10 },
      },
      variance: 0.1,
      directionality: 'none',
      cycleMode: 'sets',
      bufferBetweenSounds: true,
    },
    heartbeat: {
      isConstant: true,
      category: 'isc',
      volume: 1,
      sets: {
        systolic: 'marker_heartbeat_01_boom_ba_seq_00.ogg',
        diastolic: 'marker_heartbeat_01_boom_ba_seq_01.ogg',
      },
      intensity: {
        0.5: {
          volume: 1,
          systolic_frequency: 1 / 0.6,
          diastolic_frequency: 1 / 0.4,
        },
        1: {
          volume: 2,
          systolic_frequency: 1 / 0.425,
          diastolic_frequency: 1 / 0.325,
        },
        1.5: {
          volume: 4,
          systolic_frequency: 1 / 0.32,
          diastolic_frequency: 1 / 0.28,
        },
        2: {
          volume: 6,
          systolic_frequency: 1 / 0.18,
          diastolic_frequency: 1 / 0.22,
        },
      },
      variance: 0.1,
      directionality: 'none',
      cycleMode: 'sets',
    },
    // room: {
    //   category: 'amb',
    //   volume: 0.01,
    //   sets: {
    //     norm: 'amb_generic_room_tone_\\d{2}.exa.ogg',
    //   },
    //   intensity: {
    //     0: { volume: 0.1, frequency: 1 },
    //     2: { volume: 0.1, frequency: 1 },
    //   },
    //   variance: 0,
    //   directionality: 'none',
    //   bufferBetweenSounds: true,
    // },
    clang: {
      category: 'met',
      volume: 0.1,
      sets: [
        'amb_air_release_\\d{2}.ogg',
        'amb_glass_stress_\\d{2}.ogg',
        'amb_ship_damage_\\d{2}.ogg',
        'amb_quadshot_airvent_scuffles_\\d{2}.exa.ogg',
        'amb_quadshot_pipe_stress_(lite|med|lrg)_[a-z]_\\d{2}\\.exa\\.ogg',
        'aud_church_hallways_01_\\d{2}.ogg',
        'aud_indoc_center_01_\\d{2}.ogg',
        'aud_observation_center_01_\\d{2}.ogg',
        'aud_pastor_vent_01_\\d{2}.ogg',
        'bing_stairwell_\\d{2}.exa.ogg',
        'creepy_tram_metal_lt_\\d{2}.ogg',
        'crypt_coldsuit_room_\\d{2}.ogg',
        'prop_pipe_plates_thunk_01_\\d{2}.ogg',
        'safe_room_\\d{2}.ogg',
        'sonar_room_z01_\\d{2}.ogg',
        'ssfx_bing_stairwell_\\d{2}.exa.ogg',
        'ssfx_ship_creak_\\d{2}.exa.ogg',
        'zerog_z01_\\d{2}.ogg',
      ],
      intensity: {
        0: { volume: 0.5, frequency: 1 / 20 },
        1.5: { volume: 1, frequency: 1 / 10 },
        2: { volume: 2, frequency: 1 / 5 },
      },
      variance: 0.5,
      directionality: 'unique',
      pitchSpeedRange: [0.9, 1.1],
    },
    annc: {
      category: 'sfx',
      volume: 0.25,
      sets: 'audio_pa_02_04.exa.ogg',
      intensity: {
        0: { volume: 0.15, frequency: 1 / 45 },
        2: { volume: 0.15, frequency: 1 / 45 },
      },
      variance: 0,
      directionality: 'shared',
    },
    // guide_annc: {
    //   category: 'npc',
    //   volume: 2,
    //   sets: 'audio_pa_03_\\d{2}.exa.ogg',
    //   intensity: {
    //     0: { volume: 0.25, frequency: 1 / 2 },
    //   },
    //   variance: 0,
    //   // directionality: 'shared',
    //   cycleMode: 'files',
    //   bufferBetweenSounds: true,
    // },
    // crazy: {
    //   category: 'npc',
    //   volume: 0.25,
    //   sets: 'observation_z01_\\d{2}.ogg',
    //   intensity: { 0: { volume: 0.25, frequency: 1 } },
    //   bufferBetweenSounds: true,
    //   variance: 0,
    //   directionality: 'shared',
    // },
  },
}
